In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\data\openparliament\hansards_with_party_tokenized_en.csv")

C:\Users\alecr\Anaconda3\envs\openparliament\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (21,24,29,30,31,32,33,34) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
df.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1, inplace=True)

In [6]:
df.head()

,id,politician_id,riding_id,party_id,end_date,start_date,id.1,document_id,time,h1_en,...,who_context_en,slug,urlcache,h1_fr,h2_fr,h3_fr,who_fr,who_context_fr,wordcount_en,tokenized_content
0,2611,3465,35066,4,2005-11-29,1997-09-22,232373,1878,2001-05-03 13:50:00-04,Government Orders,...,NaN,marlene-catterall-1,/debates/2001/5/3/marlene-catterall-1/,NaN,NaN,NaN,NaN,NaN,\N,"['mr.', 'speaker', ',', 'i', 'rise', 'on', 'a'..."
1,3210,3465,70224,4,1997-04-27,1994-01-17,232373,1878,2001-05-03 13:50:00-04,Government Orders,...,NaN,marlene-catterall-1,/debates/2001/5/3/marlene-catterall-1/,NaN,NaN,NaN,NaN,NaN,\N,"['mr.', 'speaker', ',', 'i', 'rise', 'on', 'a'..."
2,4305,173,70358,1,\N,2015-10-19,645329,388,2008-02-14 13:15:00-05,Routine Proceedings,...,Parliamentary Secretary to the Leader of the G...,tom-lukiwski-7,/debates/2008/2/14/tom-lukiwski-7/,NaN,NaN,NaN,NaN,NaN,\N,"['finally', ',', 'mr.', 'speaker', ',', 'i', '..."
3,1534,173,47007,1,2015-10-19,2004-10-04,645329,388,2008-02-14 13:15:00-05,Routine Proceedings,...,Parliamentary Secretary to the Leader of the G...,tom-lukiwski-7,/debates/2008/2/14/tom-lukiwski-7/,NaN,NaN,NaN,NaN,NaN,\N,"['finally', ',', 'mr.', 'speaker', ',', 'i', '..."
4,1541,43,47014,1,2015-10-19,2004-10-04,313253,1621,2004-02-06 10:05:00-05,NaN,...,NaN,garry-breitkreuz-1,/debates/2004/2/6/garry-breitkreuz-1/,NaN,NaN,NaN,NaN,NaN,\N,"['mr.', 'speaker', ',', 'i', 'rise', 'today', ..."

In [7]:
df.columns

Index(['id', 'politician_id', 'riding_id', 'party_id', 'end_date',
       'start_date', 'id.1', 'document_id', 'time', 'h1_en', 'h2_en',
       'member_id', 'who_en', 'content_en', 'sequence_en', 'wordcount',
       'politician_id.1', 'procedural', 'h3_en', 'who_hocid', 'content_fr',
       'statement_type', 'written_question', 'source_id', 'who_context_en',
       'slug', 'urlcache', 'h1_fr', 'h2_fr', 'h3_fr', 'who_fr',
       'who_context_fr', 'wordcount_en', 'tokenized_content'],
      dtype='object')

In [12]:
utterances = df.pivot_table(index='who_en', values='wordcount', aggfunc='mean')

In [14]:
utterances.head()

                         wordcount
who_en
Alexis Brunelle-Duceppe      736.0
An hon. member                 3.0
Bob Saroya                     0.0
Dhalla, Ruby                  46.0
DubÃ©, Matthew                118.0

In [17]:
utterances.sort_values(by= 'wordcount', ascending=False)[:20]

                                                      wordcount
who_en
Hon. Mauril BÃ©langer (for the President of the ...  2975.000000
Hon. Allan Rock (for the President of the Treas...  2855.000000
Mr. Gurmant Grewal (Newtonâ€”North Delta, CPC),       2532.000000
Hon. Ethel Blondin-Andrew (Minister of State (C...  2510.333333
Right Hon. Jean ChrÃ©tien (for the Minister of S...  2252.000000
Mr. Michel Guimond (Beauportâ€”Montmorencyâ€”CÃ´te-d...  2229.000000
Hon. David Anderson (for Minister of Foreign Af...  2021.000000
Hon. Raymond Chan (for the Minister of Foreign ...  1917.000000
M. Pablo Rodriguez (HonorÃ©-Mercier, Lib.)           1898.000000
Michael Barrett                                     1878.000000
Mr. John Bryden (Ancasterâ€”Dundasâ€”Flamboroughâ€”Al...  1850.000000
Mr. Peter Stoffer (for Mr. Rick Laliberte)          1808.000000
Hon. Anne McLellan (for the Leader of the Gover...  1759.000000
Ms. Eleni Bakopanos (Ahuntsic, Lib.),               1643.000000
Hon. Martin Cauchon (Attorney General of Canada...  1585.000000
M. Scott Reid (Lanarkâ€”Carleton, Alliance canadi...  1580.000000
Mr. Lynn Myers (Parliamentary Secretary to Soli...  1491.000000
Hon. Lawrence MacAulay (for Minister of Justice...  1488.000000
Hon. Stephen Owen (Secretary of State (Indian A...  1480.000000
Hon. Andy Mitchell (for the Minister for Intern...  1457.000000

With the exception of Michael Barrett, all the biggest talkers in the house of commons are MPs who have a specific cabinet position

In [18]:
avg_party_talkers = df.pivot_table(values='wordcount',index='party_id',aggfunc='mean' )

In [19]:
avg_party_talkers.sort_values(by='wordcount', ascending=False)

           wordcount
party_id
3         286.647871
28        266.838369
25        264.015200
26        262.885154
2         259.170914
5         251.271591
1         207.347696
4         192.541338
9         191.939678
39        188.890052
46        177.296552

In [20]:
df.party_id.value_counts()

4     272399
1     264271
2     142575
3      77341
25     53883
28     45177
5      17276
26     16065
9       4907
46      2175
39       382
Name: party_id, dtype: int64

I need to export the core_party table to a csv to join for the full list, but so far, it seems that the Bloc are the biggest talkers, which surprises me, since I didn't think they tended to speak in english on the floor, given options.

In [ ]:
df[df.party_id==]